Adaptarte/Adaptarte

.gitattributes
.github/workflows/front.yml
front/package-lock.json
front/package.json
front/src/utils/notifications/types.ts

- Add gitattributes with eol=lf
- Update lock json
- Update format npm script to run on all files under src
- Add npm scripts format:check & lint:check to check without changes
- Format code
- Add workflow front to check lint & format on front changes

chore(front): #215 setup github actions

---

front/src/components/Button/index.test.tsx

- Add test suite for Button component

chore(front): #219 add button test

---

front/src/components/Button/index.tsx
front/src/components/CheckBox/index.test.tsx
front/src/components/CheckBox/index.tsx
front/src/components/Text/index.tsx

- Add test suite for CheckBox component
- Remove default prop values

chore(front): #219 add checkbox test

---

front/src/components/DailyGoal/index.test.tsx
front/src/components/DailyGoal/index.tsx
front/src/components/DailyGoal/styles.ts
front/src/components/Img/types.ts

- Add test suite for CheckBox component
- Replace timeout by simple conditional
- Replace conditional img by map

chore(front): #219 add dailygoal test

---

front/src/components/Grid/Column/index.tsx
front/src/components/Grid/Row/index.tsx
front/src/components/Grid/index.test.tsx

- Add test suite for Grid components

chore(front): #219 add grid test

---

front/src/components/Screen/index.test.tsx

- Add test suite for Screen component

chore(front): #219 add screen test

---

front/src/components/Card/index.tsx
front/src/components/ComingSoon/index.tsx
front/src/components/ComingSoon/styles.ts
front/src/components/ComingSoon/type.ts
front/src/views/Landing/DailyHabits/index.tsx
front/src/views/SignIn/index.tsx

- Add ComingSoon component for pending features
- Take Column out from Card
- Implement ComingSoon wrapper in DailyHabits and SignIn

fest(front): #219 add comingsoon component

---

front/src/components/Input/index.test.tsx

- Add test suite for Input component
- Peer-coding with @ozamiduro and @JuanCarri007

chore(front): #219 add input test

---

front/src/utils/auth/index.tsx
front/src/views/SignIn/index.tsx

- add Input for username
- add create account in auth
- add button for a space to create account

feat(front): #132 create acc with email/password

---

front/src/views/Landing/DailyHabits/index.tsx

- Check food's Habit when more than 80% of food is added

feat(front): #195 check food habit on done

---

front/src/components/Tag/index.test.tsx
front/src/components/Tag/index.tsx
front/src/components/Tag/styles.ts
front/src/components/Tag/types.ts

feat(front): #237 add tag component

---

front/src/components/Header/index.tsx
front/src/components/Tag/styles.ts
front/src/views/Consumption/index.tsx
front/src/views/Exercise/index.tsx
front/src/views/Feeding/index.tsx
front/src/views/Landing/index.tsx

- Header uses screen options' style

feat(front): #237 pass header style down

---

front/src/components/Grid/Column/index.tsx
front/src/components/Grid/Column/types.ts
front/src/components/Header/index.tsx
front/src/components/Img/index.tsx
front/src/components/Img/types.ts
front/src/components/Screen/index.tsx
front/src/components/Tag/index.tsx
front/src/components/Tag/styles.ts
front/src/components/Tag/types.ts
front/src/views/Consumption/index.tsx
front/src/views/Feeding/index.tsx
front/src/views/Landing/index.tsx

- Add prop size to Column for more width flexibility
- Render Header only if has content
- Make Img prop src more similar to Image's source
- Set Screen's default bg to WHITE
- Set Tag's default bg to GREY_LIGHT

feat(front): #237 adjust some components

---

front/src/navigation/App/index.tsx
front/src/navigation/App/types.ts
front/src/views/Landing/index.tsx
front/src/views/Profile/index.tsx
front/src/views/Profile/styles.ts

- Show header by default
- Add profile screen with basic info

feat(front): #237 add profile screen

---

front/android/app/build.gradle
front/package-lock.json

- Update npm dependencies
- Enable universalApk if the separared apk option is enabled

chore(front): #195 update dependencies

---

packages/back/.eslintrc.js
packages/back/package-lock.json
packages/back/package.json
packages/back/src/index.ts
packages/back/tsconfig.json

- Add simple api with root endpoint
- Add dependent eslint file

feat(back): #245 setup back

---

.eslintrc.js
.github/workflows/front.yml
.prettierrc.js
package-lock.json
package.json
packages/front/.eslintrc.js
packages/front/index.ts
packages/front/package.json

- Move eslint and prettier to root folder
- Setup root package.json
- Change front index extension from js to ts

chore(cross): #245 setup monorepo

---

packages/back/package-lock.json
packages/back/package.json
packages/back/src/app.ts
packages/back/src/index.ts
packages/back/tsconfig.json

- Remove dist before build with rimraf
- Add watch script based on build
- Change start to watch dist with nodemon
- Take app instanciation to app.ts

chore(back): #245 config scripts

---

packages/back/src/app.ts
packages/back/src/routes/exams/index.ts
packages/back/src/routes/exams/tension.ts
packages/back/src/routes/food/index.ts
packages/back/src/routes/food/intakes.ts
packages/back/src/routes/medicine/index.ts
packages/back/src/routes/medicine/intakes.ts
packages/back/src/routes/medicine/recipes.ts

feat(back): #245 add routers

---

packages/back/package-lock.json
packages/back/package.json

- Install firebase-functions & firebase-functions-test

chore(back): #256 install firebase functions

---

packages/back/.firebaserc
packages/back/firebase.json
packages/back/package-lock.json
packages/back/package.json
packages/back/src/index.ts

- Add firebase config files
- Update npm scripts to use firebase functions
- Setup firebase-functions with express app

chore(back): #256 setup firebase functions

---

packages/back/package-lock.json
packages/back/package.json

- Install @babel cli, core, preset-env, preset-typescript, runtime
- Install babel-plugin-module-resolver

chore(back): #259 install babel packages

---

packages/back/.eslintrc.js
packages/back/babel.config.js
packages/back/src/app.ts
packages/back/src/index.ts
packages/back/tsconfig.json

- Config babel and ts base url
- Set eslint rule simple-import-sort/imports
- Use absolute path for routes
- Fix import of firebase-functions

chore(back): #259 setup babel

---

packages/front/.gitignore
packages/front/android/app/build.gradle
packages/front/package.json

- Edit script android:bundle to remove assets generation
- Edit script android:build to not delete generated assets
- Setup keystore and signing.properties with release signing config
- Specify entry file in gradle

chore(front): #262 config android release build

---

packages/front/android/app/proguard-rules.pro
packages/front/src/views/SignIn/index.tsx

- Add realm.react proguard options
- Refac SignIn removing needless functions

fix(front): #262 update proguard-rules

---

packages/back/src/config/env.ts
packages/back/src/config/firebase.ts

- Setup environment variables
- Initialize firebase admin and auth & firestore services

feat(back): #269 setup firebase admin

---

packages/front/src/components/Carousel/index.test.tsx
packages/front/src/components/Carousel/types.ts
packages/front/src/views/Exercise/data.ts
packages/front/src/views/Exercise/index.tsx

- Add test for component Carousel
- Move Exercise data from components/CarouselCard

test(front): #219 add carousel test

---

packages/front/src/components/Carousel/index.test.tsx
packages/front/src/components/ComingSoon/index.test.tsx

- Add test for component ComingSoon

test(front): #219 add comingsoon test

---

packages/front/src/components/DatePicker/index.test.tsx
packages/front/src/components/DatePicker/index.tsx

- Add test for component DatePicker

test(front): #219 add DatePicker test

---

packages/front/src/components/Habit/index.test.tsx

- Add test for component Habit

test(front): #219 add Habit test

---

packages/front/src/components/Img/index.test.tsx
packages/front/src/components/Img/index.tsx

test(front): #219 add Img test

---

packages/front/src/components/Modal/index.test.tsx

- Add test for component Modal

test(front): #219 add Modal test

---

packages/front/src/views/Splash/index.test.tsx

test(front): #219 add Splash test

---

packages/front/src/components/Tension/index.test.tsx
packages/front/src/components/Tension/index.tsx
packages/front/src/components/Tension/types.ts
packages/front/src/views/Landing/DailyGoals/TensionGoal/index.tsx

- Decouple Tension from DB, auth and analytics implementation
- Add test for component Tension

refac(front): #219 add Tension test

---

packages/front/src/utils/date/index.test.tsx

- fix format a date
- fix convert date to string

feat(front): #219 fix date tests from utils

---

packages/front/src/views/Profile/index.tsx
packages/front/src/views/SignIn/index.tsx

- Add option from create account to return to signin
- Add C.C space in profile components

feat(front): #170 add option create acco to signin

---

packages/front/src/components/MedicineIntake/index.test.tsx
packages/front/src/components/MedicineIntake/index.tsx
packages/front/src/components/MedicineIntake/types.ts
packages/front/src/views/Landing/DailyGoals/MedicineGoal/index.tsx
packages/front/src/views/SignIn/index.tsx

- Decouple MedicineIntake from DB and auth implementation
- Add test for component MedicineIntake

refac(front): #219 add MedicineIntake test

---

packages/front/src/components/Header/index.test.tsx
packages/front/src/components/Header/index.tsx
packages/front/src/navigation/App/index.tsx

- Use title instead of headerTitle in Header
- Make Header more testable
- Add test for component Header

refac(front): #219 add Header test

---

packages/front/src/components/Carousel/CarouselCard/index.tsx
packages/front/src/components/Carousel/CarouselCard/types.ts
packages/front/src/components/Img/index.test.tsx
packages/front/src/components/Img/index.tsx
packages/front/src/components/Img/types.ts

- Make CarouselCard more testable
- Add test for component CarouselCard
- Fix Img and its test

refac(front): #219 add CarouselCard test

---

packages/back/jest.config.js
packages/back/package-lock.json
packages/back/package.json

- Install @types for superagent & supertest
- Add jest config and setup files

chore(back): #289 setup jest

---

packages/back/src/app.test.ts
packages/back/src/index.ts

- Import from firebase-functions only https
- Add root test

test(back): #289 add root test

---

packages/front/src/utils/db/firebase/index.ts
packages/front/src/utils/db/realm/index.ts
packages/front/src/utils/db/realm/schemas.ts
packages/front/src/utils/db/realm/types.ts
packages/front/src/utils/db/types.ts
packages/front/src/utils/food/index.ts
packages/front/src/views/Consumption/index.tsx
packages/front/src/views/Feeding/FoodCard/index.tsx
packages/front/src/views/Feeding/index.tsx
packages/front/src/views/Landing/DailyGoals/index.tsx
packages/front/src/views/Landing/DailyHabits/index.tsx

- Replace Realm-specific types by the more general DB types
- Rename Consumption to FoodIntake
- Add all used vars to array deps of DB hooks

refac(front): #295 update db types

---

packages/front/src/utils/db/firebase/index.ts
packages/front/src/utils/db/types.ts

- Add diet with amount of portions for food categories to type DBUser
- Add default diet in addUser
- Add type DBDoc with props id and data
- Change type of useDBUserData to DBDoc of given collection

feat(front): #295 add diet to user type

---

packages/front/src/utils/db/firebase/index.ts
packages/front/src/utils/food/index.ts
packages/front/src/views/Consumption/index.tsx
packages/front/src/views/Feeding/FoodCard/index.tsx
packages/front/src/views/Feeding/FoodCard/types.ts
packages/front/src/views/Feeding/index.tsx

- Remove filter dep from useEffect on useDBUserData to avoid re-render
- Replace realm by firebase in Feeding

chore(front): #305 migrate db foodintakes

---

packages/front/ios/Adaptarte.xcodeproj/project.pbxproj
packages/front/ios/Adaptarte/Adaptarte.entitlements
packages/front/ios/Podfile.lock
packages/front/package-lock.json
packages/front/package.json
packages/front/src/utils/auth/index.tsx
packages/front/src/views/SignIn/index.tsx

- Add button to login with apple ID
- fix format and lint in sign in and auth

feat(front): #132 add apple auth

---

packages/front/src/utils/db/firebase/index.ts
packages/front/src/utils/medicine/index.ts
packages/front/src/views/Landing/DailyGoals/MedicineGoal/index.tsx
packages/front/src/views/Landing/DailyGoals/index.tsx

- Add firebase util to convert all timestamp object in date
- Replace realm by firebase in MedicineIntakes

refac(front): #305 migrate db medicineintakes

---

packages/front/src/components/DailyGoal/index.tsx
packages/front/src/components/Habit/index.tsx
packages/front/src/components/MedicineIntake/index.test.tsx
packages/front/src/utils/auth/index.tsx
packages/front/src/views/Feeding/index.tsx
packages/front/src/views/Profile/index.tsx
packages/front/src/views/SignIn/index.tsx

- Update code to follow lint rule react/jsx-sort-props

style(front): lint code

---

packages/front/src/views/Landing/DailyGoals/TensionGoal/index.tsx
packages/front/src/views/Landing/DailyGoals/index.tsx

- Replace realm by firebase in Tension

refac(front): #305 migrate db tension

---

packages/front/src/components/MedicineIntake/index.test.tsx
packages/front/src/components/MedicineIntake/index.tsx
packages/front/src/components/MedicineIntake/types.ts
packages/front/src/utils/db/realm/types.ts
packages/front/src/utils/db/types.ts
packages/front/src/utils/medicine/data.ts
packages/front/src/utils/medicine/index.ts
packages/front/src/utils/notifications/index.ts
packages/front/src/views/Landing/DailyGoals/MedicineGoal/index.tsx
packages/front/src/views/Landing/DailyGoals/MedicineGoal/types.ts
packages/front/src/views/Landing/DailyGoals/index.tsx

- Migrate from type SchemaType to DBDoc

refac(front): #305 migrate realm types

---

packages/front/package-lock.json
packages/front/package.json
packages/front/src/utils/medicine/data.ts

- Uninstall realm, @realm/react

chore(front): #305 uninstall realm

---

packages/front/src/components/Header/index.test.tsx

- Add useEffect to navigate in test Header

test(front): #219 fix test for header

---

packages/front/src/components/DataDose/data.ts
packages/front/src/components/DataDose/index.test.tsx

- Add util weightedRandom to  pick elements with distinct probabilities
- Add groups for each data dose matter
- Pick data dose using weightedRandom

refac(front): #303 pick dose with weight

---

packages/front/src/components/Button/styles.ts
packages/front/src/components/CheckBox/index.tsx
packages/front/src/components/CheckBox/types.ts
packages/front/src/components/MedicineIntake/types.ts
packages/front/src/components/Modal/types.ts
packages/front/src/components/Tension/types.ts

- Set Button's default color to GLAUCOUS
- Add prop style to CheckBox
- Add type ModalBaseProps to extend easier

refac(front): #303 adjust components

---

packages/front/src/utils/db/firebase/index.ts
packages/front/src/utils/db/types.ts
packages/front/src/views/Profile/EditDiseases/index.test.tsx
packages/front/src/views/Profile/EditDiseases/index.tsx
packages/front/src/views/Profile/EditDiseases/styles.ts
packages/front/src/views/Profile/EditDiseases/types.ts

- Add diseases to DBUser type
- Add EditDiseases to Profile

feat(front): #303 add editdiseases form

---

packages/front/android/app/build.gradle
packages/front/package-lock.json
packages/front/package.json
packages/front/src/components/Icon/index.tsx
packages/front/src/components/Icon/types.ts

- add icons config for android
- add new components for icons

feat(front): #324 add icons config for android

---

packages/front/src/views/Panic/index.tsx
packages/front/src/views/Panic/styles.ts

- add redirectioring to call when pressing icon
- add phone icon

feat(front): #301 add redirectioring to call

---

packages/front/ios/Adaptarte.xcodeproj/project.pbxproj
packages/front/ios/Adaptarte.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
packages/front/ios/Adaptarte/Info.plist
packages/front/ios/Podfile.lock

feat(front) #324 add icon config for iOS

---

packages/front/src/views/Panic/data.ts

- fix error of phone numbers when we try to call in iOS

fix(front) #301 fix error from data

---

packages/front/src/utils/db/types.ts
packages/front/src/views/Profile/Diseases/index.test.tsx
packages/front/src/views/Profile/Diseases/index.tsx
packages/front/src/views/Profile/Diseases/styles.ts
packages/front/src/views/Profile/Diseases/translations.ts
packages/front/src/views/Profile/Diseases/types.ts
packages/front/src/views/Profile/EditDiseases/index.test.tsx
packages/front/src/views/Profile/EditDiseases/index.tsx
packages/front/src/views/Profile/EditDiseases/types.ts
packages/front/src/views/Profile/index.tsx

- Add Diseases to load and set user's diseases in Profile

feat(front): #303 add profile/diseases

---

packages/front/src/components/Carousel/CarouselCard/index.tsx
packages/front/src/components/Carousel/CarouselCard/types.ts
packages/front/src/components/Carousel/index.tsx
packages/front/src/components/Carousel/types.ts
packages/front/src/components/Exercises/index.tsx
packages/front/src/components/Exercises/types.ts
packages/front/src/utils/analytics/analytics.ts
packages/front/src/utils/db/types.ts
packages/front/src/views/Exercise/data.ts
packages/front/src/views/Exercise/types.ts

- add exercise registry
- add Exercise component to register exercise
- add exercise element in utils db for register exercise data in db
- add new element to register exercise in analytics
- fix Carousel Card type
- implement Exercise in Carousel

feat(front): #298 add exercise registry

---

packages/front/src/components/Carousel/CarouselCard/types.ts
packages/front/src/components/Carousel/types.ts
packages/front/src/views/Exercise/index.tsx
packages/front/src/views/Exercise/styles.ts
packages/front/src/views/Exercise/types.ts

- fix exercise spellin in all directory

fix(front): #298 fix exercise spelling

---

packages/front/src/components/DataDose/data.ts
packages/front/src/components/DataDose/index.test.tsx
packages/front/src/components/DataDose/index.tsx
packages/front/src/components/DataDose/types.ts
packages/front/src/utils/patient.ts
packages/front/src/views/Landing/index.tsx
packages/front/src/views/Profile/Diseases/index.tsx

- Add patient util fillDiseases to get undefined diseases as false
- Add util getDataDoses to consider user's diseases
- Edit DataDose to get user's diseases

feat(front): #303 get datadoses with disease

---

.github/workflows/front.yml
packages/front/package.json

- Add npm scripts format:check & lint:check
- Update job lint in workflow front to only check lint & format

ci(front): #298 update job lint

---

packages/front/src/components/Carousel/CarouselCard/index.tsx
packages/front/src/components/Carousel/index.tsx
packages/front/src/components/Exercises/index.tsx
packages/front/src/components/Icon/index.tsx
packages/front/src/views/Panic/index.tsx

- Remove lint errors running npm run lint & npm run format

style(front): #298 remove lint errors

---

packages/front/src/components/DataDose/data.ts
packages/front/src/components/DataDose/index.test.tsx
packages/front/src/components/DataDose/types.ts
packages/front/src/types/dataDoses.ts

- Add const WEIGHTS for weighted probability of data dose groups
- Replace and move type IDataDose by TDataDose
- Update DataDose test
- Add type TDataDoseGroup to have both data doses and its weight
- Update getDataDoses to return TDataDoseGroup[]

feat(front): #303 get data doses with its weight

---

packages/front/src/components/DataDose/data.ts

- Add data doses specific for hypertension

feat(front): #303 add hypertension datadoses

---

packages/front/src/components/DataDose/data.ts

- Add data doses specific for EPOC

feat(front): #303 add epoc datadoses

---

packages/front/src/components/DataDose/data.ts
packages/front/src/utils/db/types.ts
packages/front/src/utils/patient.ts
packages/front/src/views/Profile/Diseases/translations.ts
packages/front/src/views/Profile/EditDiseases/index.tsx

- Add diseases diabetes mellitus & heart failure

feat(front): #303 add remaining diseases

---

packages/front/src/components/DataDose/data.ts

- Add data doses specific for diabetes mellitus & heart failure

feat(front): #303 add remaining disease data doses

---

packages/front/src/components/DataDose/data.ts

feat(front): #299 add carer data doses

---

packages/front/src/views/Profile/index.tsx

- Add key to Diseases in Profile to identify data changes

fix(front): #303 add key to diseases

---

packages/front/src/components/DataDose/data.ts
packages/front/src/views/Exercise/data.ts
packages/front/src/views/Exercise/translations.ts

- Update advices in Exercise habit to take into account all diseases
- Add data dose for exercise hydration

feat(front): #303 update exercise data

---

packages/front/src/components/DataDose/data.ts

- Add data doses related to stress management

feat(front): #302 add data doses for stress

---

packages/front/src/navigation/App/index.tsx
packages/front/src/navigation/App/types.ts
packages/front/src/views/Calm/index.tsx
packages/front/src/views/Calm/styles.ts
packages/front/src/views/Calm/translations.ts
packages/front/src/views/Landing/DailyHabits/index.tsx

- Add basic Calm view
- Add navigation to Calm from DailyHabits

feat(front): #302 add calm view

---

packages/front/jest.config.js
packages/front/src/components/Icon/index.test.tsx
packages/front/src/components/Icon/index.tsx
packages/front/src/views/Panic/index.tsx

- Rename IconF to Icon
- Add react-native-vector-icons to es modules in jest config
- Add test for Icon

refac(front): #324 adjust icon

---

packages/front/src/components/EditableText/index.test.tsx
packages/front/src/components/EditableText/index.tsx
packages/front/src/components/EditableText/styles.ts
packages/front/src/components/EditableText/types.ts
packages/front/src/components/Input/index.tsx
packages/front/src/components/Input/styles.ts

- Set vertical padding of Input to 2
- Add component EditableText to allow to modify text information shown

feat(front): #350 add editable text

---

packages/front/src/views/Panic/index.tsx
packages/front/src/views/Panic/styles.ts

- change color to contact and note container

style(front): #301 fix style in Panic

---

packages/front/src/components/DataDose/data.ts

- add medicine indications and contras for data dose

feat(front): #304 add medicine indications

---

packages/front/src/utils/db/types.ts
packages/front/src/views/Panic/data.ts
packages/front/src/views/Panic/index.tsx
packages/front/src/views/Panic/styles.ts
packages/front/src/views/SignIn/index.tsx

- add a box with EditableText and Button to save contact info
- add new interface for db with emergency contacts
- fix operator that user complete all fields to login in the app

feat(front): #356 add option to save contacts

---

packages/front/src/components/EditableText/index.test.tsx
packages/front/src/components/EditableText/index.tsx
packages/front/src/utils/db/firebase/index.ts
packages/front/src/utils/patient.ts

- Call change handler only when the save button is pressed
- Trigger onChange only when the value has actually changed
- Accept undefined in fillDiseases
- Use fillDiseases in util addUser

fix(front): #350 fix editable text onchange

---

packages/front/src/utils/db/types.ts
packages/front/src/views/Profile/BasicInfo/index.test.tsx
packages/front/src/views/Profile/BasicInfo/index.tsx
packages/front/src/views/Profile/BasicInfo/styles.ts
packages/front/src/views/Profile/BasicInfo/translations.ts
packages/front/src/views/Profile/BasicInfo/types.ts

- Add basicInfo to type DBUser with id & phone
- Add section BasicInfo for Profile

feat(front): #358 add patient basic info

---

packages/front/src/views/Profile/index.tsx
packages/front/src/views/Profile/styles.ts

- Add section BasicInfo to Profile

feat(front): #358 add basic info to profile

---

packages/front/src/utils/db/types.ts
packages/front/src/views/modals/WeightRecord/index.test.tsx
packages/front/src/views/modals/WeightRecord/index.tsx
packages/front/src/views/modals/WeightRecord/translations.ts
packages/front/src/views/modals/WeightRecord/types.ts

- Add type DBWeight
- Add modal view WeightRecord with kg & date

feat(front): #343 add weight record

---

packages/front/src/views/Landing/DailyGoals/TensionGoal/index.tsx
packages/front/src/views/Landing/DailyGoals/WeightGoal/index.tsx
packages/front/src/views/Landing/DailyGoals/WeightGoal/types.ts
packages/front/src/views/Landing/DailyGoals/index.tsx

- Add WeightGoal for weight daily goals
- Remove medicine analytics from tension registry

feat(front): #343 add weight goal

---

packages/front/src/views/Landing/DailyGoals/TensionGoal/index.tsx
packages/front/src/views/modals/TensionRecord/index.test.tsx
packages/front/src/views/modals/TensionRecord/index.tsx
packages/front/src/views/modals/TensionRecord/types.ts

- Move Tension to views/modals
- Rename Tension as TensionRecord

refac(front): #343 move tension modal

---

packages/front/src/components/Carousel/CarouselCard/index.tsx
packages/front/src/components/Carousel/index.tsx
packages/front/src/views/modals/ExerciseRecord/index.tsx
packages/front/src/views/modals/ExerciseRecord/types.ts

- Move Exercises to views/modals
- Rename Exercises as ExerciseRecord

refac(front): #298 move exercise modal

---

packages/front/src/views/modals/ExerciseRecord/index.tsx
packages/front/src/views/modals/ExerciseRecord/translations.ts
packages/front/src/views/modals/ExerciseRecord/types.ts

- Add ExerciseRecord translations file
- Add DatePicker for exercise

feat(front): #298 add date to exercise record

---

packages/front/src/views/modals/ExerciseRecord/index.test.tsx

- Add test suite for ExerciseRecord

test(front): #298 add exercise record test

---

packages/front/src/views/modals/DiseasesEdit/index.test.tsx
packages/front/src/views/modals/DiseasesEdit/index.tsx
packages/front/src/views/modals/DiseasesEdit/translations.ts

- Add translations file for DiseasesEdit

refac(front): #358 add diseaseedit translations

---

packages/front/src/views/modals/TensionRecord/index.test.tsx
packages/front/src/views/modals/TensionRecord/index.tsx
packages/front/src/views/modals/TensionRecord/translations.ts

- Add translations file for TensionRecord
- Add test for incorrect data

feat(front): #358 add translations to tension

---

packages/front/src/components/Carousel/CarouselCard/index.tsx
packages/front/src/components/CheckBox/index.tsx

- Remove state handling in component Checkbox
- Remove redundant TouchableOpacity + Checkbox in Carousel

refac(front): #298 remove checkbox state

---

packages/front/src/views/Panic/index.tsx
packages/front/src/views/modals/MedicineIntakeRecord/index.test.tsx
packages/front/src/views/modals/MedicineIntakeRecord/index.tsx
packages/front/src/views/modals/MedicineIntakeRecord/translations.ts

- Add translations file to MedicineIntakeRecord
- Use beforeEach for rendering in test

refac(front): #318 add medicine intake translations

---

packages/front/src/views/Landing/DailyHabits/index.test.tsx
packages/front/src/views/Landing/DailyHabits/index.tsx
packages/front/src/views/Landing/DailyHabits/translations.ts
packages/front/src/views/Landing/DailyHabits/types.ts
packages/front/src/views/Landing/index.tsx

- Add translations file for Daily Habits
- Receive completion of habits as props
- Add tests for rendering and navigation

refac(front): #318 refactor & test daily habits

---

packages/front/src/components/Img/index.test.tsx
packages/front/src/components/Img/index.tsx
packages/front/src/views/Consumption/index.tsx
packages/front/src/views/Consumption/styles.ts
packages/front/src/views/Feeding/AddConsumption/index.test.tsx
packages/front/src/views/Feeding/AddConsumption/index.tsx
packages/front/src/views/Feeding/AddConsumption/styles.ts
packages/front/src/views/Feeding/AddConsumption/types.ts

- Add testId to component Img
- Replace img plus with icon
- Add tests to AddConsumption for render & press

refac(front): #318 refactor & test addconsumption

---

packages/front/src/components/DataDose/data.ts
packages/front/src/components/DataDose/index.tsx
packages/front/src/components/DataDose/types.ts
packages/front/src/utils/datadose/index.ts

- add imgs in data for datadose
- add new type for imgs in datadose type
- refactor data only for tips & details
- add new file in utils for datadose elements

feat(front): #373 add imgs & refactor datadose

---

packages/front/src/utils/food/types.ts
packages/front/src/views/Feeding/FoodCard/index.test.tsx
packages/front/src/views/Feeding/FoodCard/index.tsx
packages/front/src/views/Feeding/FoodCard/styles.ts
packages/front/src/views/Feeding/FoodCard/types.ts
packages/front/src/views/Feeding/index.tsx

- Move delete out of FoodCard using prop onDelete
- Replace img close by icon
- Add tests for render & delete
- Other minor refactorings

refac(front): #318 refactor & test foodcard

---

packages/front/src/components/Icon/index.tsx
packages/front/src/components/Img/index.tsx
packages/front/src/views/Profile/Header/index.test.tsx
packages/front/src/views/Profile/Header/index.tsx
packages/front/src/views/Profile/Header/styles.ts
packages/front/src/views/Profile/Header/types.ts
packages/front/src/views/Profile/index.tsx
packages/front/src/views/Profile/styles.ts

- Use solid icons only
- Add default testId for imgs without name
- Add Profile Header with user's name & photo

refac(front): #318 refactor & test profile header

---

packages/front/src/components/CheckBox/index.tsx
packages/front/src/components/CheckBox/styles.ts
packages/front/src/components/Header/index.tsx
packages/front/src/components/Icon/index.tsx
packages/front/src/components/Icon/types.ts
packages/front/src/components/Img/index.test.tsx
packages/front/src/components/Modal/index.test.tsx
packages/front/src/components/Modal/index.tsx
packages/front/src/components/Modal/styles.ts
packages/front/src/views/Exercise/index.tsx
packages/front/src/views/Exercise/styles.ts
packages/front/src/views/Landing/index.tsx
packages/front/src/views/Landing/styles.ts

- Replace img close by icon times
- Replace text ✓ by icon check
- Replace img back by icon arrow-left
- Replace img profile by icon user-circle

refac(front): #324 migrate to icons

---

packages/front/jest.setup.ts
packages/front/src/utils/auth/index.tsx
packages/front/src/views/Authentication/Providers/index.test.tsx
packages/front/src/views/Authentication/Providers/index.tsx
packages/front/src/views/Authentication/Providers/styles.ts
packages/front/src/views/Authentication/Providers/translations.ts
packages/front/src/views/Authentication/index.tsx
packages/front/src/views/Authentication/styles.ts

- Refactor & mock utils to sign-in with providers
- Move authentication with providers to new component

refac(front): #318 isolate auth providers

---

packages/front/jest.setup.ts
packages/front/src/views/Authentication/SignIn/index.test.tsx
packages/front/src/views/Authentication/SignIn/index.tsx
packages/front/src/views/Authentication/SignIn/styles.ts
packages/front/src/views/Authentication/SignIn/translations.ts

- Mock util signInEmailPassword
- Modularize sign-in in view Authentication/SignIn

refac(front): #318 add view auth sign-in

---

packages/front/jest.setup.ts
packages/front/src/utils/auth/index.tsx
packages/front/src/views/Authentication/SignUp/index.test.tsx
packages/front/src/views/Authentication/SignUp/index.tsx
packages/front/src/views/Authentication/SignUp/styles.ts
packages/front/src/views/Authentication/SignUp/translations.ts

- Mock util signUpEmailPassword
- Update displayName on sign-up
- Modularize sign-up in view Authentication/SignUp
- Add tests for rendering, sign-up & disabling

refac(front): #318 modularize auth sign-up

---

packages/front/src/views/Authentication/SignUp/translations.ts
packages/front/src/views/Authentication/index.test.tsx
packages/front/src/views/Authentication/index.tsx
packages/front/src/views/Authentication/translations.ts

-  Replace old auth implementation by toggleable SignIn & SignUp

feat(front): #318 update view auth

---

packages/front/src/components/Carousel/index.test.tsx
packages/front/src/components/Carousel/index.tsx
packages/front/src/components/Carousel/types.ts
packages/front/src/views/Exercise/index.tsx

- add Carousel Card for Carousel test
- move auth and firebase connection from Carousel to Exercise

fix(front): #219 fix Carousel test

---

packages/front/src/utils/db/firebase/index.ts
packages/front/src/utils/db/index.tsx
packages/front/src/utils/db/types.ts
packages/front/src/views/Consumption/index.tsx
packages/front/src/views/Exercise/index.tsx
packages/front/src/views/Feeding/index.tsx
packages/front/src/views/Landing/DailyGoals/MedicineGoal/index.tsx
packages/front/src/views/Landing/DailyGoals/TensionGoal/index.tsx
packages/front/src/views/Landing/DailyGoals/WeightGoal/index.tsx
packages/front/src/views/Landing/DailyGoals/index.tsx
packages/front/src/views/Landing/index.tsx
packages/front/src/views/Panic/index.tsx
packages/front/src/views/Profile/index.tsx

- Add db type DBOperations for db CRUD operations
- Add hook useDB that returns DBOperations functions
- Replace useDBUser by db.getUser
- Replace update user implementation by db.updateUser
- Replace useDbUserData by db.getDocs
- Replace addUserData by db.addDoc
- Replace delUserData by db.delDoc
- Remove firebase utils addUserData & delUserData

feat(front): #390 add hook useDB

---

packages/front/src/components/Carousel/CarouselCard/types.ts
packages/front/src/components/Carousel/index.tsx
packages/front/src/components/Carousel/types.ts
packages/front/src/views/Exercise/index.tsx

- Remove unused props from Carousel & its card
- Remove redundant state management for done exercise

refac(front): #298 clean exercise's code

---

packages/front/jest.setup.ts
packages/front/src/views/Landing/index.test.tsx
packages/front/src/views/Landing/index.tsx
packages/front/src/views/Landing/styles.ts
packages/front/src/views/Landing/translations.ts

- Mock lib @notifee
- Mock utils useUser & useDB
- Add translations file
- Fix panicBtn style
- Add tests for rendering & navigation

test(front): #318 test landing

---

.github/workflows/front.yml

- Add dispatch to workflow front

ci(front): #394 allow running front ci manually

---

packages/front/src/views/Landing/index.tsx
packages/front/src/views/Landing/styles.ts
packages/front/src/views/Panic/data.ts
packages/front/src/views/Panic/index.tsx
packages/front/src/views/Panic/translations.ts

- add symptoms for each diseases
- add a function to get symptoms depending the user illness
- add the user img in Landing view

feat(front): #301 add symptoms in Panic view

---

packages/front/src/views/Panic/index.tsx
packages/front/src/views/Panic/translations.ts

- add general symptoms if disease doesn't select yet

feat(front): #301 add general symptoms

---

package-lock.json

- Run npm i to update npm packages

chore(front): #402 update packages

---

packages/front/src/components/List/index.test.tsx
packages/front/src/components/List/index.tsx
packages/front/src/components/List/types.ts

feat(front): #402 add component list

---

packages/front/src/views/Calm/index.test.tsx
packages/front/src/views/Calm/index.tsx
packages/front/src/views/Calm/styles.ts
packages/front/src/views/Calm/translations.ts
packages/front/src/views/Calm/types.ts

- Add stress consequences & calm description
- Add test
- Add array & type for calm activities

feat(front): #402 add calm content

---

packages/front/src/utils/db/types.ts
packages/front/src/views/Calm/index.test.tsx
packages/front/src/views/Calm/index.tsx
packages/front/src/views/Calm/translations.ts

- Add type DBCalmActivity
- Add list of toggleable buttons for calm activities

feat(front): #402 add calm registry

---

packages/front/src/views/Splash/index.test.tsx
packages/front/src/views/modals/TensionRecord/Abnormal/index.test.tsx
packages/front/src/views/modals/TensionRecord/Abnormal/index.tsx
packages/front/src/views/modals/TensionRecord/Abnormal/styles.ts
packages/front/src/views/modals/TensionRecord/Abnormal/translations.ts
packages/front/src/views/modals/TensionRecord/Abnormal/types.ts
packages/front/src/views/modals/TensionRecord/index.test.tsx
packages/front/src/views/modals/TensionRecord/index.tsx

- Add modal TensionRecord/Abnormal to show on unexpected tension values
- Refactor Splash screen test

feat(front): #342 show abnormal tension alert

---

packages/front/src/components/DailyGoal/styles.ts
packages/front/src/styles/colors.ts
packages/front/src/utils/db/firebase/index.ts
packages/front/src/views/Landing/index.tsx
packages/front/src/views/Landing/styles.ts
packages/front/src/views/Panic/styles.ts
packages/front/src/views/Profile/Diseases/index.tsx

- Show patient's score in Landing
- Rename color YELLOW as YELLOW_LIGHT and add color YELLOW
- Fix profile img size in Landing
- Remove db util addUser

feat(front): #344 show score

---

packages/front/src/utils/engagement/score.ts
packages/front/src/utils/engagement/types.ts
packages/front/src/views/Calm/index.tsx
packages/front/src/views/Consumption/index.tsx
packages/front/src/views/Exercise/index.tsx
packages/front/src/views/Feeding/index.tsx
packages/front/src/views/Landing/DailyGoals/MedicineGoal/index.tsx
packages/front/src/views/Landing/DailyGoals/TensionGoal/index.tsx
packages/front/src/views/Landing/DailyGoals/WeightGoal/index.tsx
packages/front/src/views/Landing/index.tsx

- Add hook useScore with value & add func
- Use score.add in Calm, Food, Exercise, Medicine, Tension & Weight
- Use score.value in Landing

feat(front): #344 add score

---

packages/front/jest.setup.ts
packages/front/src/views/Landing/index.tsx
packages/front/src/views/modals/NotificationsPermission/index.test.tsx
packages/front/src/views/modals/NotificationsPermission/index.tsx
packages/front/src/views/modals/NotificationsPermission/styles.ts
packages/front/src/views/modals/NotificationsPermission/translations.ts

- Add modal NotificationPermission to ask for notifications permission
- Show NotificationPermission in Landing
- Mock Notifee.requestPermission

fix(front): #413 ask notifications permission

---

packages/web/package-lock.json
packages/web/package.json
packages/web/src/App.tsx
packages/web/src/index.tsx
packages/web/src/styles.scss

- Install bootstrap & override colors dark & light
- Add default styles to main container

chore(web): #416 setup bootstrap

---

packages/web/package-lock.json
packages/web/package.json

- Install firebase & react-router-dom

chore(web): #416 install firebase & router

---

packages/web/src/components/Button/index.tsx
packages/web/src/components/Input/index.test.tsx
packages/web/src/components/Input/index.tsx
packages/web/src/components/Input/types.ts

feat(web): #420 add input

---

packages/web/src/components/Button/index.tsx
packages/web/src/components/Button/types.ts
packages/web/src/components/Input/index.test.tsx
packages/web/src/components/Input/index.tsx
packages/web/src/components/Input/types.ts
packages/web/src/components/Paper/index.test.tsx
packages/web/src/components/Paper/index.tsx
packages/web/src/components/Paper/types.ts

- Add component Paper
- Add Button & Input className
- Add Input change handler to receive string instead of event callback

feat(web): #420 add paper

---

packages/web/src/App.tsx
packages/web/src/views/Authentication/index.test.tsx
packages/web/src/views/Authentication/index.tsx
packages/web/src/views/Authentication/translations.ts

- Add demo view Authentication
- Create simple router

feat(web): #420 add view auth

---

packages/front/jest.setup.ts
packages/front/src/components/List/index.tsx
packages/front/src/navigation/App/index.tsx
packages/front/src/views/Landing/index.test.tsx
packages/front/src/views/Landing/index.tsx
packages/front/src/views/Landing/translations.ts
packages/front/src/views/Profile/Header/index.tsx
packages/front/src/views/Profile/Header/styles.ts
packages/front/src/views/Profile/index.test.tsx
packages/front/src/views/Profile/index.tsx
packages/front/src/views/Profile/styles.ts
packages/front/src/views/Profile/translations.ts

- fix header color 
- move panic button from Landing to Profile
- add Profile tests
- add translation for Profile
- improve details in style
- add score in Profile
- fix lint, format & test

style(front): #423 improve Profile details

---

packages/web/src/utils/db/types.ts

- Add db types at utils/db/types

chore(web): #420 add db types

---

packages/web/src/views/Landing/PatientInfo/index.test.tsx
packages/web/src/views/Landing/PatientInfo/index.tsx
packages/web/src/views/Landing/PatientInfo/translations.ts
packages/web/src/views/Landing/PatientInfo/types.ts
packages/web/src/views/Landing/index.tsx
packages/web/src/views/Landing/translations.ts

- Add patient search bar
- Add patient basic info

feat(web): #420 add patient search & info

---

packages/web/src/index.html
packages/web/src/styles.scss
packages/web/src/utils/db/types.ts
packages/web/src/views/Landing/PatientInfo/index.tsx
packages/web/src/views/Landing/PatientInfo/translations.ts

- Redesign PatientInfo to use Papers for each info
- Scale html viewport to display properly on mobile
- Edit gutter to match the spacing values
- Show diseases in PatientInfo
- Edit DB diseases to be array instead of object with booleans
- Add edit button on PatientInfo

feat(web): #420 add patient diseases

---

packages/web/src/views/Landing/MedicineRecipe/index.tsx
packages/web/src/views/Landing/MedicineRecipe/translations.ts
packages/web/src/views/Landing/MedicineRecipe/types.ts
packages/web/src/views/Landing/index.tsx
packages/web/src/views/Landing/translations.ts

- Add MedicineRecipe for with recipe info & edit and delete actions
- Show demo medicine recipe

feat(web): #420 show medicine recipes

---

packages/web/package-lock.json
packages/web/package.json

- Install dotenv to read environment variables

chore(web): #416 install dotenv

---

.prettierrc.js
packages/web/src/utils/firebase/config.ts
packages/web/src/utils/firebase/firestore.ts

- Initialize firebase app with auth & firestore
- Add firebase utils for db operations

chore(web): #437 setup firebase

---

packages/web/src/components/Modal/index.test.tsx
packages/web/src/components/Modal/index.tsx
packages/web/src/components/Modal/translations.ts
packages/web/src/components/Modal/types.ts

- Add Modal component to show important information on top

feat(web): #420 add modal

---

packages/web/src/components/Switch/index.test.tsx
packages/web/src/components/Switch/index.tsx
packages/web/src/components/Switch/types.ts

- Add component Switch to toggle boolean values

feat(web): #420 add switch

---

packages/web/src/components/Modal/types.ts
packages/web/src/components/Switch/index.test.tsx
packages/web/src/components/Switch/index.tsx
packages/web/src/components/Switch/types.ts
packages/web/src/utils/db/types.ts
packages/web/src/views/Landing/PatientInfo/index.tsx

- Extend input props to match names and add className
- Rollback user diseases to record of booleans
- Separate ModalVisibilityProps from ModalProps

feat(web): #420 improve switch

---

packages/web/src/views/Landing/PatientInfo/Edit/index.test.tsx
packages/web/src/views/Landing/PatientInfo/Edit/index.tsx
packages/web/src/views/Landing/PatientInfo/Edit/translations.ts
packages/web/src/views/Landing/PatientInfo/Edit/types.ts
packages/web/src/views/Landing/PatientInfo/index.tsx

- Add modal PatientInfo/Edit with active status & diseases

feat(web): #420 add patient info edit

---

packages/web/src/components/Button/index.tsx
packages/web/src/components/Button/types.ts
packages/web/src/views/Landing/MedicineRecipe/Add/index.test.tsx
packages/web/src/views/Landing/MedicineRecipe/Add/index.tsx
packages/web/src/views/Landing/MedicineRecipe/Add/translations.ts
packages/web/src/views/Landing/MedicineRecipe/Add/types.ts
packages/web/src/views/Landing/index.tsx
packages/web/src/views/Landing/translations.ts

- Add modal MedicineRecipe/Add
- Add prop disabled to Button

feat(web): #420 add medicine recipe add

---

packages/web/src/components/Input/index.tsx
packages/web/src/components/Input/types.ts
packages/web/src/views/Authentication/index.test.tsx
packages/web/src/views/Authentication/index.tsx
packages/web/src/views/Authentication/translations.ts

- Add Authentication form with Email & Password

feat(web): #420 add authentication form

---

packages/web/src/App.tsx
packages/web/src/utils/auth/index.ts
packages/web/src/views/Authentication/index.tsx
packages/web/src/views/Landing/index.tsx
packages/web/src/views/Landing/translations.ts

- Add auth utils signIn, signOut & useAuth
- Add sign-out button at Landing
- Handle sign-in in Authentication & App

feat(web): #437 add authentication

---

packages/web/package.json
packages/web/src/views/Landing/MedicineRecipe/index.test.tsx
packages/web/src/views/Landing/MedicineRecipe/index.tsx
packages/web/src/views/Landing/MedicineRecipe/translations.ts
packages/web/src/views/Landing/index.tsx

- Remove prop takeFrom from medicine recipe
- Add MedicineRecipe test
- Set build script up with webpack

feat(web): #420 remove takefrom of medicinerecipe

---

packages/web/src/utils/db/types.ts
packages/web/src/utils/firebase/firestore.ts

- Add util timestampsToDate to parse dates
- Type DBDoc as possibly undefined
- Add util listenCol & listenDoc to listen collections & docs

feat(web): #437 add db listeners

---

packages/web/src/components/Select/index.test.tsx
packages/web/src/components/Select/index.tsx
packages/web/src/components/Select/translations.ts
packages/web/src/components/Select/types.ts

feat(web): #420 add select

---

packages/front/src/utils/db/types.ts
packages/web/src/components/Select/index.tsx
packages/web/src/components/Select/types.ts
packages/web/src/views/Landing/PatientSearch/index.tsx
packages/web/src/views/Landing/PatientSearch/types.ts
packages/web/src/views/Landing/index.tsx

- Add Landing/PatientSearch to select a patient
- Add prop className to Select
- Update type DBUser in front

feat(cross): #420 add patient search

---

packages/web/src/utils/db/index.ts
packages/web/src/utils/db/types.ts
packages/web/src/views/Landing/PatientSearch/index.tsx
packages/web/src/views/Landing/index.tsx

- Add useDB hook with common DBOperations for given user
- Fix PatientSearch between uid & user.id (dni)
- Load user info in Landing/MedicineRecipe

feat(web): #437 add db hook

---

packages/web/src/views/Authentication/index.tsx

- Center sign-in form and set max-width

feat(web): #420 enhance auth ui

---

packages/web/package-lock.json
packages/web/package.json
packages/web/src/App.tsx
packages/web/src/utils/charts.ts
packages/web/webpack.config.js

- Install chart.js & react-chartjs-2
- Register chartjs elements when the app starts

chore(web): #420 add chartjs

---

packages/web/jest.setup.ts
packages/web/src/views/Landing/Dashboard/LineChart/index.tsx
packages/web/src/views/Landing/Dashboard/LineChart/types.ts
packages/web/src/views/Landing/Dashboard/Stat/index.test.tsx
packages/web/src/views/Landing/Dashboard/Stat/index.tsx
packages/web/src/views/Landing/Dashboard/Stat/types.ts

- Add Dashboard/Stat to show numeric statistics
- Add Dashboard/LineChart to show line charts
- Mock react-chartjs-2 Line

fear(web): #420 add linechart & dashboard stat

---

packages/web/src/utils/db/index.ts
packages/web/src/utils/db/types.ts
packages/web/src/utils/firebase/firestore.ts
packages/web/src/views/Landing/Dashboard/index.test.tsx
packages/web/src/views/Landing/Dashboard/index.tsx
packages/web/src/views/Landing/Dashboard/translations.ts
packages/web/src/views/Landing/Dashboard/types.ts
packages/web/src/views/Landing/PatientSearch/index.tsx
packages/web/src/views/Landing/index.tsx

- Add Dashboard with statistics and charts
- Add db query constraint to sort docs by date
- Remove optional from DBDoc' data
- Hidde Landing user-related sections when it's not selected a patient
- Make PatientSearch sticky on top

feat(web): #420 add dashboard

---

packages/web/.firebaserc
packages/web/.gitignore
packages/web/firebase.json
packages/web/webpack.config.js

- Setup firebase hosting on web app

feat(web): #416 deploy web

---

packages/front/src/utils/db/index.tsx
packages/front/src/utils/db/types.ts

- implement function to updateDocs

feat(front): #305 implement updateDocs

---

packages/front/src/views/Profile/BasicInfo/index.tsx
packages/front/src/views/Profile/BasicInfo/styles.ts
packages/front/src/views/Profile/BasicInfo/translations.ts
packages/front/src/views/Profile/BasicInfo/types.ts
packages/front/src/views/Profile/index.tsx
packages/front/src/views/Profile/translations.ts
packages/front/src/views/modals/PatientInfoEdit/index.tsx

- Replace EditableText by Modal PatientInfoEdit to edit patient's info
- Disable edit if there are no changes

feat(front): #465 update basic info editing

---

packages/web/jest.setup.ts
packages/web/src/utils/contexts/index.tsx
packages/web/src/utils/db/index.ts

- Split getDB from useDB to use useMemo instead of several useCallback
- Add context useDBPatient to access database operations
- Mock useDBPatient in jest

refac(front): #470 memoize usedb

---

packages/web/src/utils/db/types.ts
packages/web/src/views/Landing/MedicineRecipes/Add/index.tsx
packages/web/src/views/Landing/MedicineRecipes/Card/index.test.tsx
packages/web/src/views/Landing/MedicineRecipes/Card/index.tsx
packages/web/src/views/Landing/MedicineRecipes/Card/translations.ts
packages/web/src/views/Landing/MedicineRecipes/Card/types.ts
packages/web/src/views/Landing/MedicineRecipes/index.tsx
packages/web/src/views/Landing/MedicineRecipes/translations.ts
packages/web/src/views/Landing/index.tsx
packages/web/src/views/Landing/translations.ts

- Load medicine recipes from DB
- Allow to add and delete medicine recipes

feat(front): #470 allow write & read medicines

---

packages/front/src/views/Profile/Header/index.tsx
packages/front/src/views/Profile/Header/styles.ts

- Set container width to 100% in order to work the align
- Remove redundant nested containers to center again & set zIndex

refac(front): #423 clean profile header code

---

packages/front/src/components/Screen/styles.ts
packages/front/src/views/Profile/Header/styles.ts
packages/front/src/views/Profile/index.tsx
packages/front/src/views/Profile/styles.ts

- Replace the fixed minHeight with flex-end in the profile container
- Replace header's absolute position with negative margin in the photo
- Others minor adjustments

fix(front): #423 fix profile responsiveness

---

packages/web/src/App.test.tsx
packages/web/src/views/Landing/Dashboard/index.tsx
packages/web/src/views/Landing/Dashboard/utils.ts
packages/web/src/views/Landing/MedicineRecipes/Card/index.test.tsx
packages/web/src/views/Landing/MedicineRecipes/Card/index.tsx
packages/web/src/views/Landing/MedicineRecipes/Card/translations.ts

- Add util getFoodsChartData to manipulate food records to plot them
- Remove edit button from MedicineRecipesCard

feat(web): #470 add foods chart

---

packages/web/src/views/Landing/Dashboard/index.tsx
packages/web/src/views/Landing/Dashboard/utils.ts

- Generalize getFoodsChartData as docsToLineChartByDate
- Add LineChart for calms

feat(web): #470 add calms chart

---

packages/front/src/utils/form/fields.ts
packages/front/src/views/Authentication/SignIn/index.tsx
packages/front/src/views/Authentication/SignUp/index.tsx
packages/front/src/views/modals/ExerciseRecord/index.tsx
packages/front/src/views/modals/PatientInfoEdit/index.tsx
packages/front/src/views/modals/TensionRecord/index.tsx
packages/front/src/views/modals/WeightRecord/index.tsx

- Add field utils to disable save buttons on empty or NaN values

feat(front): #485 add field utils

---

packages/front/src/utils/db/types.ts
packages/front/src/utils/medicine/data.ts
packages/front/src/utils/medicine/index.ts
packages/front/src/utils/medicine/types.ts

- Remove prop amount of DBMedicineRecipe & rename takeFrom as date
- Add util getMedicineGoals to get recipes with today's intakes & goals

feat(front): #487 add util getmedicinegoals

---

packages/front/src/utils/db/types.ts
packages/front/src/utils/medicine/index.ts
packages/front/src/utils/notifications/index.ts
packages/front/src/views/Landing/DailyGoals/MedicineGoal/index.tsx
packages/front/src/views/Landing/DailyGoals/MedicineGoal/types.ts
packages/front/src/views/Landing/DailyGoals/index.tsx
packages/front/src/views/Landing/index.tsx
packages/front/src/views/modals/MedicineIntakeRecord/index.test.tsx

- Make DBUser props optional
- Fix error in getMedicineGoals moving date consts to top
- Change addMedicineNotification props to date + recipe

feat(front): #487 load medicines from db

---

packages/web/src/views/Landing/Dashboard/index.tsx
packages/web/src/views/Landing/Dashboard/utils.ts

- Add record's weight support to docsToLineChartByDate
- Add linecharts for exercises and medicine intakes

feat(web): #470 add missing charts

---

packages/front/src/utils/medicine/index.ts
packages/front/src/views/Calm/translations.ts
packages/front/src/views/Profile/Header/styles.ts

- Treat medicine recipe as possibly undefined in groupMedicines
- Wrap patient's diseases to next line and center them
- Tell patient to register their calm activities

fix(front): #494 fix minor app bugs

---

packages/front/src/views/Hydration/index.tsx
packages/front/src/views/Hydration/styles.ts

- Add score.add to handleSave dependencies to fix the score resetting
- Remove all useState (unneeded)
- Memo progressAnimated & extrapolate to waterHeight %
- Remove unneeded bottleSize & handleLayout
- Remove unneeded containers & closing tag of <Animated.View>
- Style bottle img with fixed size & improve other styles

fix(front): #494 keep score at hydration

---

packages/web/src/views/Landing/Dashboard/LineChart/index.tsx
packages/web/src/views/Landing/Dashboard/LineChart/types.ts
packages/web/src/views/Landing/Dashboard/index.tsx
packages/web/src/views/Landing/Dashboard/translations.ts

- Add prop axes to LineChart and set the scales title options
- Add axes to charts tension, weight & exercise

feat(web): #423 add chart axes name

---

packages/web/src/utils/db/download.ts
packages/web/src/utils/db/types.ts
packages/web/src/utils/files/index.ts
packages/web/src/views/Landing/index.tsx
packages/web/src/views/Landing/translations.ts

- Add util getDBData to retrieve all the information of active users
- Add utils downloadFile & saveJson
- Add  a download button to download the db in a json file

feat(web): #500 allow to download db

---

packages/front/src/components/Notice/index.test.tsx
packages/front/src/components/Notice/index.tsx
packages/front/src/components/Notice/styles.ts
packages/front/src/components/Notice/types.ts
packages/front/src/views/Feeding/translations.ts
packages/front/src/views/Panic/index.tsx
packages/front/src/views/Panic/styles.ts

- add a component Notice for confirmation an action
- add icon Trash for contact emergency
- add option to delete contact emergency

feat(front): #356 delete contact emergency

---

packages/front/src/utils/db/index.tsx
packages/front/src/utils/db/types.ts
packages/front/src/views/Panic/index.tsx
packages/front/src/views/modals/PatientInfoEdit/index.tsx

fix(front): #505 fix error to save user info

---

packages/front/src/components/DataDose/DataDoseCard/index.tsx
packages/front/src/components/DataDose/DataDoseCard/styles.ts
packages/front/src/components/DataDose/index.test.tsx
packages/front/src/components/DataDose/index.tsx
packages/front/src/views/Hydration/index.tsx
packages/front/src/views/Hydration/translation.ts
packages/front/src/views/Landing/index.tsx

- add option to change datadose info
- change hydration goal

feat(front): #508 change datadose info

---

packages/front/src/views/Landing/DailyGoals/index.tsx

- organize daily goals according to their dates

feat(front): #511 organize daily goals

---

packages/front/src/views/Landing/index.tsx

- change Calm's checkbox when completed

feat(front): #509 change Calm's checkbox

---

packages/front/jest.config.js
packages/front/package-lock.json
packages/front/package.json
packages/front/src/App.tsx
packages/front/src/utils/toast/config.tsx
packages/front/src/utils/toast/toast.ts
packages/front/src/views/Authentication/Providers/index.tsx
packages/front/src/views/Authentication/SignIn/index.tsx
packages/front/src/views/Authentication/SignUp/index.tsx
packages/front/src/views/Exercise/index.tsx
packages/front/src/views/Panic/index.tsx
packages/front/src/views/modals/ExerciseRecord/index.tsx
packages/front/src/views/modals/MedicineIntakeRecord/index.tsx
packages/front/src/views/modals/PatientInfoEdit/index.tsx
packages/front/src/views/modals/TensionRecord/index.tsx
packages/front/src/views/modals/WeightRecord/index.tsx

- add toast
- add toast config
- add 4 types of toast
- add toast for notify the user in different actions

feat(front): #518 add toast
